/**
 * Rule-based content quality scoring (Phase 5, section 9.3 of
 * docs/LEARNING_EXPERIENCE_REDESIGN_AGENT.md).
 *
 * The spec's literal checklist assumes structured fields that this app's
 * Lesson model (src/models/Lesson.ts) does not have: there is no separate
 * "examples" array, no "target words" list, and no stored quiz/answer-key
 * data (confirmed by the evaluation layer's doc comment in evaluation.ts —
 * `content` is just a free-text string). This module adapts the abstract
 * "base 50, +10 per signal, cap 100" formula to signals that actually exist
 * on a Lesson, documented per-heuristic below:
 *
 *   - has examples (+10): approximated as "content has multiple distinct
 *     lines/sentences", since a single fragment can't demonstrate usage in
 *     context the way a worked example does. Vocab-style `- word: def`
 *     bullets count as examples too (each bullet is one example entry).
 *   - has target words (+10): for vocab lessons specifically, content using
 *     the `- word: definition` bullet format (the same shape parsed by
 *     VocabLessonView, src/components/learning/views/VocabLessonView.tsx)
 *     is treated as a literal target-word list. For other lesson types,
 *     there is no structured vocabulary field to check, so this dimension
 *     degrades to partial credit based on content richness (enough
 *     distinct words) rather than forcing a literal mapping.
 *   - has clear prompt (+10): title is non-empty and reasonably descriptive
 *     (length-based heuristic), AND content is not just a single short
 *     fragment (some minimum word count).
 *   - has evaluation questions (+10): this app has no per-lesson stored
 *     quiz/answer-key data (Task 3/7 confirmed evaluation is generated at
 *     request time, not stored on Lesson). "Evaluable" is therefore
 *     type-determined here rather than lesson-specific: listening and vocab
 *     lessons can always have a quiz generated/graded by the evaluation
 *     layer (see evaluateListening/evaluateVocab in evaluation.ts and the
 *     listening-quiz fallback generation from Task 7), so they get full
 *     credit. Writing/dev_english/speaking are evaluated from free-text
 *     input rather than a quiz, so they get partial credit for this
 *     dimension (the lesson is still "evaluable", just not via a quiz).
 *   - reasonable length (+10): content word count falls in a sensible
 *     range — not a one-line stub, not an unreasonably long wall of text.
 *     Uses wordsCount when present (vocab lessons set it), otherwise counts
 *     words in `content` directly.
 *
 * Pure function, no DB access — callers are responsible for fetching/
 * persisting the Lesson document.
 */

export type QualityScoringLesson = {
  title?: string | null
  type?: string | null
  content?: string | null
  wordsCount?: number | null
  estimatedMinutes?: number | null
}

const BASE_SCORE = 50
const SIGNAL_BONUS = 10
const MAX_SCORE = 100

function countWords(text: string | null | undefined): number {
  if (!text) return 0
  return text
    .trim()
    .split(/\s+/)
    .filter((word) => word.length > 0).length
}

function countNonEmptyLines(text: string | null | undefined): number {
  if (!text) return 0
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0).length
}

function isVocabBulletFormat(line: string): boolean {
  // Matches the `- word: definition` shape generated by
  // generateVocabLessons() (src/server/external/generate-lessons-from-cache.ts)
  // and parsed by VocabLessonView's parseVocabEntries().
  const withoutBullet = line.replace(/^-\s*/, '')
  return withoutBullet.includes(':')
}

function hasExamples(content: string | null | undefined): boolean {
  const lines = (content ?? '')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)

  // Multiple distinct lines/sentences count as demonstrating usage in
  // context. A single short fragment does not.
  if (lines.length >= 2) return true

  return countWords(content) >= 8
}

function hasTargetWords(lesson: QualityScoringLesson): boolean {
  const content = lesson.content ?? ''
  const lines = content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)

  if (lesson.type === 'vocab') {
    const bulletLines = lines.filter(isVocabBulletFormat)
    // At least a handful of structured word entries.
    return bulletLines.length >= 3
  }

  // No structured vocabulary field for other types — degrade to a content
  // richness proxy: enough distinct words to plausibly carry vocabulary.
  const uniqueWords = new Set(
    content
      .toLowerCase()
      .split(/\W+/)
      .filter((word) => word.length > 2)
  )
  return uniqueWords.size >= 8
}

function hasClearPrompt(lesson: QualityScoringLesson): boolean {
  const title = (lesson.title ?? '').trim()
  if (title.length < 6) return false

  return countWords(lesson.content) >= 4
}

function hasEvaluationQuestions(lesson: QualityScoringLesson): boolean {
  // "Evaluable" is type-determined: listening/vocab can always have a quiz
  // generated and graded (see evaluation.ts). Other types are evaluated via
  // free-text heuristics rather than a quiz, so they only get the partial
  // credit handled in computeQualityScore (half of the bonus).
  return lesson.type === 'listening' || lesson.type === 'vocab'
}

function partialEvaluationCredit(lesson: QualityScoringLesson): boolean {
  return (
    lesson.type === 'writing' ||
    lesson.type === 'dev_english' ||
    lesson.type === 'speaking'
  )
}

function hasReasonableLength(lesson: QualityScoringLesson): boolean {
  const wordCount =
    typeof lesson.wordsCount === 'number' && lesson.wordsCount > 0
      ? lesson.wordsCount
      : countWords(lesson.content)

  const lineCount = countNonEmptyLines(lesson.content)

  // Too short: basically a stub. Too long: not realistic for a single
  // 5-10 minute daily micro-lesson.
  if (wordCount < 4 && lineCount < 2) return false
  if (wordCount > 400) return false

  return true
}

/**
 * Computes a 0-100 quality score for a lesson, per section 9.3.
 *
 * base 50
 * +10 has examples
 * +10 has target words
 * +10 has clear prompt
 * +10 has evaluation questions (full credit for listening/vocab,
 *     half credit for writing/dev_english/speaking)
 * +10 reasonable length
 * cap 100
 */
export function computeQualityScore(lesson: QualityScoringLesson): number {
  let score = BASE_SCORE

  if (hasExamples(lesson.content)) {
    score += SIGNAL_BONUS
  }

  if (hasTargetWords(lesson)) {
    score += SIGNAL_BONUS
  }

  if (hasClearPrompt(lesson)) {
    score += SIGNAL_BONUS
  }

  if (hasEvaluationQuestions(lesson)) {
    score += SIGNAL_BONUS
  } else if (partialEvaluationCredit(lesson)) {
    score += SIGNAL_BONUS / 2
  }

  if (hasReasonableLength(lesson)) {
    score += SIGNAL_BONUS
  }

  return Math.max(0, Math.min(MAX_SCORE, Math.round(score)))
}
